* Ein Keyboard, mein Keybaord. Hoffentlich ein gutes.

I need a layout for
- typing in english and german
- for coding, meaning symbols and shortcuts must be easy to reach
- gamingin is out of scope. I just use another keyboard.

** layouts

** Current Layout: a modified Hands Down
A  [[https://www.reddit.com/r/KeyboardLayouts/comments/1djzkv1/comment/l9onx07/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button][modified]]
    [[https://sites.google.com/alanreiser.com/handsdown][Hands Down]] layout where au and ie are easy would be nice. Seems like
    #+BEGIN_SRC
    v g l þ *  * u o , z
    c s n t m  k i e a h
    x f w d b  j y ' . p
            r  ⎵
    #+END_SRC

    coild be nice. I should add some linger and some adaptive keys.
    - `l þ` -> `ld`
    - `y` -> `you` ? (Maybe but where to put home row mods!?)
    - ` `a` -> `ä` (u,o,s the same)

    I do not like to shoft with combos and the umlauts are not nice!
** Experiments
*** OPY
    based on [[https://gitlab.com/voidyourwarranty/yackboard/-/blob/main/layout.md][this]] and [[https://opylayout.wordpress.com/2023/01/21/the-opy-layout/][that]]
    Not for me!
*** Magic Sturdy
    [[https://github.com/getreuer/qmk-keymap][Pascals version]].
    #+BEGIN_SRC
    V M L C P            B ^ U O , /
    S T R D Y            F N E A I '
    X K J G W            Z H , . ;
            ⎵ ⇥     / @ ⇧
    #+END_SRC

*** Focal-keyboard-layout
    #+BEGIN_SRC
    v l h g k   q f o u j
    s r n t b   y c a e i
    z x m d p   ' w . ; ,
    #+END_SRC

    I need to find a solution for ei an ie as it is both a very common bigrams in German.
    An alternative could be the [[https://oxey.dev/dhorf/index.html][Dhorf layout]].
*** Beakl 19
Could be nice?!
    #+BEGIN_SRC
    q . o u j  w d n m ,
    h a e i k  g s r t p
    z ' / y x  b c l f v
    #+END_SRC

* Thumb Shift or Thumb Alpha?
I need to decide on it and I need to find out which key to put on it?

* Magic and stuff
I use the [[https://github.com/klausweiss/zmk/blob/fix/adaptive-keys/docs/docs/behaviors/antecedent-morph.md][Antecedent Morph]] to emove some silly
patterns.

** Numwords
is awsome. I loved on [[QMK]] and there is a ZMK [[https://github.com/dhruvinsh/zmk-num-word][port]]

** Tri-State for Swapping.
see [[https://github.com/dhruvinsh/zmk-tri-state][this]] [[Github]] repository.

** Magic on a Thumb.
 in [[https://github.com/joa/graphite][joa's graphite]] layout he uses a thumb for shift on hold and magic on tap. This could
 be an option too.

* Sources and Inspirations
- [Anachron](https://github.com/theol0403/anachron-zmk-config/blob/master/README.md) is pretty nice!
- [[https://www.jonashietala.se/blog/2022/08/28/the_t-342_keyboard_layout/][The T34]] layout.
- [[Antecedent Morph Example][https://github.com/MikeSE314/zmk-config]]
- [[https://github.com/getreuer/qmk-keymap][Pascal Getreuer]]
- [[https://colemaq.github.io/variants.htm][Colemaq]]
- Bredfields [[https://github.com/bredfield/zmk-config/tree/main][ZMK config]]
- [[Reiners small thingy](https://github.com/reinier/rlkeymaps)
- [[Ben Valek](https://configure.zsa.io/voyager/layouts/7qMvx/latest/0)
- [[Zilp Zalp](https://github.com/kilipan/zilpzalp/tree/main/example_keymaps)
- [[A nice layout](https://github.com/bmijanovich/zmk-config/tree/db86a4ab0b10cd5cf6fdc51bdc25e31719cac70a)
- [[numbers and symbols](https://raw.githubusercontent.com/bredfield/zmk-config/main/images/30%20Key.png)
- https://docs.google.com/document/d/1_a5Nzbkwyk1o0bvTctZrtgsee9jSP-6I0q3A0_9Mzm0/edit#heading=h.uy0p1j6rzpsl
- https://cyanophage.github.io/playground.html?layout=jcyfkzl,uq=rsthdmnaio%27/vgpbxw.;-%5Ce
- https://github.com/moutis/zmk-Zen/blob/main/config/corne-ish_zen.l_alpha-HD-vb.dtsi
- https://www.reddit.com/r/KeyboardLayouts/comments/1e2jzra/bestperforming_layout_in_my_comparison_beats_both/


* My Hands Down Version
** VV with 

#+BEGIN_SRC
v w m g j    # u o " '
s c n t k    , i e a h
x p l d b    - y / . f
      r
#+END_SRC
